replicaCount: 3

image:
  repository: sanaeabahcine371/petclinic1
  tag: latest

ingress:
  enabled: false

autoscaling:
  enabled: true  # Change to true to enable Horizontal Pod Autoscaler

service:
  type: LoadBalancer  # Change to LoadBalancer to expose the service externally
